Repository geezers-io/frolic-backend, pull requests merged in 2023-02, with the labels that each got.

#39 feat: 코틀린 DSL 변경으로 인한 도커 수정 & 운용 환경에 대한 변수 파일 분리
  .gitignore
  Dockerfile
  build.gradle.kts
  conf/local/.local.mariadb.env
  conf/local/.local.spring.example.env
  conf/local/nginx/nginx.conf
  conf/spring/.example.env
  conf/spring/application.example.yaml
  src/main/resources/application-jwt-config.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-system.yaml
  src/main/resources/application.yaml
Labels: feature

#40 feat: 로컬 파일 업로드 재작성 ( 다른 로직은 다음 PR에 )_
  src/main/java/com/frolic/sns/RestfulServerApplication.java
  src/main/java/com/frolic/sns/global/common/file/api/FileDownloadApi.java
  src/main/java/com/frolic/sns/global/common/file/api/UploadApi.java
  src/main/java/com/frolic/sns/global/common/file/application/FileManageable.java
  src/main/java/com/frolic/sns/global/common/file/application/FileManager.java
  src/main/java/com/frolic/sns/global/common/file/application/LocalFileManager.java
  src/main/java/com/frolic/sns/global/common/file/application/S3FileManager.java
  src/main/java/com/frolic/sns/global/common/file/config/FIleManagerConfiguration.java
  src/main/java/com/frolic/sns/global/common/file/dto/FileInfo.java
  src/main/java/com/frolic/sns/global/common/file/model/ApplicationFile.java
  src/main/java/com/frolic/sns/global/common/file/repository/FileRepository.java
  src/main/java/com/frolic/sns/global/config/security/SpringSecurityConfiguration.java
  src/main/java/com/frolic/sns/global/config/spring/JavaMailerConfiguration.java
  src/main/java/com/frolic/sns/global/config/spring/SmsTwilioConfiguration.java
  src/main/java/com/frolic/sns/global/config/spring/WebConfiguration.java
  src/main/java/com/frolic/sns/post/api/PostCrudApi.java
  src/main/java/com/frolic/sns/post/application/PostCrudManagerImpl.java
  src/main/java/com/frolic/sns/post/application/PostFileManagerImpl.java
  src/main/java/com/frolic/sns/post/dto/CreatePostRequestV2.java
  src/main/java/com/frolic/sns/post/model/Post.java
  src/main/java/com/frolic/sns/post/model/PostFile.java
  src/main/java/com/frolic/sns/post/repository/FileRepository.java
  src/test/java/com/frolic/sns/global/common/file/application/ApplicationFileExtensionTest.java
  src/test/java/com/frolic/sns/global/common/file/application/LocalApplicationFileManagerTest.java
  src/test/java/unit/file/ApplicationFileUtilTest.java
Labels: refactor, feature

#41 feat: 로컬 파일 업로드 구현 & 게시글 관리 api v2 초안 작성
  build.gradle.kts
  src/main/java/com/frolic/sns/global/common/file/api/UploadApi.java
  src/main/java/com/frolic/sns/global/common/file/application/FileManageable.java
  src/main/java/com/frolic/sns/global/common/file/application/LocalFileManager.java
  src/main/java/com/frolic/sns/global/common/file/application/S3FileManager.java
  src/main/java/com/frolic/sns/global/common/file/dto/FileInfo.java
  src/main/java/com/frolic/sns/global/common/file/model/ApplicationFile.java
  src/main/java/com/frolic/sns/global/common/jwt/JwtEntityLoader.java
  src/main/java/com/frolic/sns/post/api/PostCrudApi.java
  src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
  src/main/java/com/frolic/sns/post/application/PostCrudManagerImpl.java
  src/main/java/com/frolic/sns/post/application/v2/HashTagManager.java
  src/main/java/com/frolic/sns/post/application/v2/PostCrudManagerV2.java
  src/main/java/com/frolic/sns/post/dto/v2/CreatePostRequest.java
  src/main/java/com/frolic/sns/post/dto/v2/PostInfo.java
  src/main/java/com/frolic/sns/post/model/PostFile.java
  src/main/java/com/frolic/sns/post/repository/HashtagDslRepository.java
  src/main/java/com/frolic/sns/post/repository/PostFileDslRepository.java
  src/main/java/com/frolic/sns/post/repository/PostFileRepository.java
Labels: feature

#42 feat: 게시글 API v2 생성, 수정, 삭제 기능 추가
  src/main/java/com/frolic/sns/global/common/file/application/LocalFileManager.java
  src/main/java/com/frolic/sns/global/common/file/config/FIleManagerConfiguration.java
  src/main/java/com/frolic/sns/global/common/file/dto/FileInfo.java
  src/main/java/com/frolic/sns/post/api/PostCrudApi.java
  src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
  src/main/java/com/frolic/sns/post/application/v2/CreatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/v2/HashTagManager.java
  src/main/java/com/frolic/sns/post/application/v2/PostCrudManagerV2.java
  src/main/java/com/frolic/sns/post/application/v2/UpdatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/dto/v2/UpdatePostRequest.java
  src/main/java/com/frolic/sns/post/model/Post.java
  src/main/java/com/frolic/sns/post/model/PostHashTag.java
  src/main/java/com/frolic/sns/post/repository/HashtagDslRepository.java
  src/main/java/com/frolic/sns/post/repository/PostFileDslRepository.java
  src/main/resources/application-system.yaml
Labels: feature

#44 feat: 파일 관리 객체 설계 개선
  src/main/java/com/frolic/sns/global/common/file/api/UploadApi.java
  src/main/java/com/frolic/sns/global/common/file/application/LocalFileManager.java
  src/main/java/com/frolic/sns/global/common/file/application/S3FileManager.java
  src/main/java/com/frolic/sns/global/common/file/config/FIleManagerConfiguration.java
  src/main/java/com/frolic/sns/global/common/file/dto/FileInfo.java
Labels: refactor, feature

#45 chore: 배포 환경 도커 컴포즈 스크립트 작성
  conf/prod/.local.spring.example.env
  conf/prod/docker-compose.yaml
  conf/prod/nginx/nginx.conf
Labels: feature

#46 chore: 배포 환경 도커 스크립트 개선
  conf/prod/docker-compose.yaml
  conf/prod/nginx/nginx.conf
Labels: feature

#37 feat: 임시 비밀번호 발급 및 이메일로 전송하는 기능 작성
  src/main/java/com/frolic/sns/RestfulServerApplication.java
  src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
  src/main/java/com/frolic/sns/auth/application/finder/EmailFindManager.java
  src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
  src/main/java/com/frolic/sns/auth/application/finder/UserInfoFinderSubManageable.java
  src/main/java/com/frolic/sns/auth/application/finder/common/FinderConstants.java
  src/main/java/com/frolic/sns/auth/dto/UserTempPasswordRequest.java
  src/main/java/com/frolic/sns/auth/dto/UserTempPasswordResponse.java
  src/main/java/com/frolic/sns/global/config/spring/JavaMailerConfiguration.java
  src/main/java/com/frolic/sns/user/repository/UserRepository.java
  src/test/java/com/frolic/sns/auth/api/UserTempPasswordApiTest.java
  src/test/java/com/frolic/sns/auth/application/finder/SendTempPasswordManagerTest.java
Labels: test, feature
