Repository geezers-io/frolic-backend, pull requests merged in 2023-01, with the labels that each got.

#5 feat: add docs code for auth api specification documentation
  src/main/java/com/modular/restfulserver/auth/api/AuthApi.java
  src/main/java/com/modular/restfulserver/auth/swagger/AuthSchemas.java
  src/main/java/com/modular/restfulserver/auth/swagger/LoginDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/LogoutDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/ReissueTokenDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/SignupDocs.java
  src/main/java/com/modular/restfulserver/global/config/swagger/SwaggerConfig.java
  src/main/java/com/modular/restfulserver/global/swagger/CommonAuthError.java
  src/main/java/com/modular/restfulserver/global/swagger/SwaggerCommonErrorSchema.java
  src/main/java/com/modular/restfulserver/global/swagger/SwaggerCommonHeaderSchema.java
Labels: documentation

#7 feat: add user management api doc
  src/main/java/com/modular/restfulserver/user/api/UserManagementApi.java
  src/main/java/com/modular/restfulserver/user/swagger/GetUserByUsernameDocs.java
  src/main/java/com/modular/restfulserver/user/swagger/UserDeleteDocs.java
  src/main/java/com/modular/restfulserver/user/swagger/UserInfoDocs.java
  src/main/java/com/modular/restfulserver/user/swagger/UserManagementSchemas.java
  src/main/java/com/modular/restfulserver/user/swagger/UserPasswordUpdateDocs.java
  src/main/java/com/modular/restfulserver/user/swagger/UserUpdateDocs.java
Labels: documentation

#6 docs: apply message utils to opendocs code
  src/main/java/com/modular/restfulserver/auth/swagger/LoginDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/LogoutDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/ReissueTokenDocs.java
  src/main/java/com/modular/restfulserver/auth/swagger/SignupDocs.java
  src/main/java/com/modular/restfulserver/global/swagger/SwaggerMessageUtils.java
Labels: documentation

#9 docs: add feed api specification docs code for api docs
  src/main/java/com/modular/restfulserver/article/api/PostCrudApi.java
  src/main/java/com/modular/restfulserver/article/api/PostLikeApi.java
  src/main/java/com/modular/restfulserver/article/swagger/ArticleDisLikeDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/ArticleLikeDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/ArticleSchemas.java
  src/main/java/com/modular/restfulserver/article/swagger/CreateArticleDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/DeleteArticleDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetArticleDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetArticleListMySelfDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetMainArticleListDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/SearchArticleDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/UpdateArticleDocs.java
Labels: documentation

#10 docs: add comment api docs
  src/main/java/com/modular/restfulserver/article/api/CommentCrudApi.java
  src/main/java/com/modular/restfulserver/article/swagger/CommentSchemas.java
  src/main/java/com/modular/restfulserver/article/swagger/CreateCommentDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/DeleteCommentDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetCommentDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetCommentListByUsernameDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/GetCommentListDocs.java
  src/main/java/com/modular/restfulserver/article/swagger/UpdateCommentDocs.java
Labels: documentation

#11 chore: add swagger config for test server
  conf/spring/application.example.dev.yaml
  conf/spring/application.example.prod.yaml
  src/main/java/com/modular/restfulserver/article/model/File.java
  src/main/java/com/modular/restfulserver/global/common/file/application/CustomFile.java
Labels: documentation

#12 fix: change server.address env for fix UnknownHostException
  conf/spring/application.example.prod.yaml
Labels: bug

#13 fix: change SPRING_DATASOURCE_URL Host env for DB Host Failed Error
  conf/spring/.example.env
Labels: bug

#18 fix: change rename QArticle to QPost for correct queryDsl build
  src/main/java/com/modular/restfulserver/post/repository/PostRepositoryDslImpl.java
Labels: bug

#17 refactor: change dto, service name for more meaningfully and refactor dto valid and add dto init test
  src/main/java/com/modular/restfulserver/auth/api/AuthApi.java
  src/main/java/com/modular/restfulserver/auth/application/AuthManageable.java
  src/main/java/com/modular/restfulserver/auth/application/AuthManager.java
  src/main/java/com/modular/restfulserver/auth/dto/TokenInfo.java
  src/main/java/com/modular/restfulserver/auth/dto/UserLoginRequest.java
  src/main/java/com/modular/restfulserver/auth/dto/UserSignupRequest.java
  src/main/java/com/modular/restfulserver/auth/swagger/AuthSchemas.java
  src/main/java/com/modular/restfulserver/auth/util/AuthConstant.java
  src/main/java/com/modular/restfulserver/auth/util/AuthValidationMessages.java
  src/main/java/com/modular/restfulserver/global/config/security/JwtConstants.java
  src/main/java/com/modular/restfulserver/global/util/message/FieldError.java
  src/main/java/com/modular/restfulserver/global/util/message/ValidationMessage.java
  src/main/java/com/modular/restfulserver/global/util/models/BaseTimeAuditing/CreateAndModifiedTimeAuditEntity.java
  src/main/java/com/modular/restfulserver/post/dto/CommentInfo.java
  src/main/java/com/modular/restfulserver/post/dto/CreateCommentRequest.java
  src/main/java/com/modular/restfulserver/post/dto/PostInfo.java
  src/main/java/com/modular/restfulserver/post/model/Comment.java
  src/main/java/com/modular/restfulserver/post/model/Post.java
  src/main/java/com/modular/restfulserver/post/util/PostValidationMessages.java
  src/main/java/com/modular/restfulserver/user/dto/UserInfo.java
  src/main/java/com/modular/restfulserver/user/dto/UserIntegrationInfo.java
  src/main/java/com/modular/restfulserver/user/model/User.java
  src/main/java/com/modular/restfulserver/user/util/UserValidationMessages.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSigninApiTest.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSignupApiTest.java
  src/test/java/com/modular/restfulserver/auth/dto/TokenInfoDtoTest.java
  src/test/java/com/modular/restfulserver/auth/dto/UserLoginRequestTest.java
  src/test/java/com/modular/restfulserver/post/dto/CommentInfoTest.java
  src/test/java/com/modular/restfulserver/user/dto/UserInfoTest.java
  src/test/java/util/MockData.java
Labels: refactor, test

#19 feat: extend user login response schema for client request
  src/main/java/com/modular/restfulserver/auth/api/AuthApi.java
  src/main/java/com/modular/restfulserver/auth/application/AuthManageable.java
  src/main/java/com/modular/restfulserver/auth/application/AuthManager.java
  src/main/java/com/modular/restfulserver/auth/dto/TokenInfo.java
  src/main/java/com/modular/restfulserver/auth/dto/UserLoginResponse.java
  src/main/java/com/modular/restfulserver/auth/swagger/AuthSchemas.java
  src/main/java/com/modular/restfulserver/user/api/UserManagementApi.java
  src/main/java/com/modular/restfulserver/user/application/UserFollowManageable.java
  src/main/java/com/modular/restfulserver/user/application/UserFollowManager.java
  src/main/java/com/modular/restfulserver/user/application/UserFollowManagerImpl.java
  src/main/java/com/modular/restfulserver/user/application/UserManageable.java
  src/main/java/com/modular/restfulserver/user/application/UserManager.java
  src/main/java/com/modular/restfulserver/user/application/UserManagerImpl.java
  src/main/java/com/modular/restfulserver/user/dto/UserUnitedInfo.java
  src/main/java/com/modular/restfulserver/user/swagger/UserManagementSchemas.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSigninApiTest.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSignupApiTest.java
  src/test/java/com/modular/restfulserver/auth/dto/TokenDetailsDtoTest.java
  src/test/java/com/modular/restfulserver/post/dto/CommentInfoTest.java
  src/test/java/com/modular/restfulserver/user/dto/UserDetailTest.java
  src/test/java/util/MockData.java
  src/test/java/util/MockProvider.java
Labels: refactor, feature

#21 feat: add phone number to user features of entire of application
  src/main/java/com/modular/restfulserver/auth/application/AuthManager.java
  src/main/java/com/modular/restfulserver/auth/dto/UserSignupRequest.java
  src/main/java/com/modular/restfulserver/global/util/message/CommonMessageUtils.java
  src/main/java/com/modular/restfulserver/post/dto/PostInfo.java
  src/main/java/com/modular/restfulserver/user/api/UserFollowManagementApi.java
  src/main/java/com/modular/restfulserver/user/application/UserFollowManageable.java
  src/main/java/com/modular/restfulserver/user/application/UserFollowManager.java
  src/main/java/com/modular/restfulserver/user/application/UserManager.java
  src/main/java/com/modular/restfulserver/user/dto/UserInfo.java
  src/main/java/com/modular/restfulserver/user/dto/UserUnitedInfo.java
  src/main/java/com/modular/restfulserver/user/dto/UserUpdateRequest.java
  src/main/java/com/modular/restfulserver/user/model/User.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSignupApiTest.java
Labels: feature

#22 test: add user test that handle it information
  src/main/java/com/modular/restfulserver/user/application/UserManager.java
  src/main/java/com/modular/restfulserver/user/dto/PasswordUpdateRequest.java
  src/main/java/com/modular/restfulserver/user/dto/UserUpdateRequest.java
  src/main/java/com/modular/restfulserver/user/model/User.java
  src/main/java/com/modular/restfulserver/user/repository/UserRepository.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSigninApiTest.java
  src/test/java/com/modular/restfulserver/auth/api/AuthSignupApiTest.java
  src/test/java/com/modular/restfulserver/user/api/GetUserInfoApiTest.java
  src/test/java/com/modular/restfulserver/user/api/UpdateUserInfoApiTest.java
  src/test/java/com/modular/restfulserver/util/MockProvider.java
  src/test/java/com/modular/restfulserver/util/TestAuthProvider.java
  src/test/java/com/modular/restfulserver/util/TestUser.java
Labels: test

#24 feat: add lettuce (redis) in spring boot application
  build.gradle
  src/main/java/com/frolic/sns/global/config/spring/RedisConfiguration.java
Labels: feature

#25 test: add redis client test
  src/test/java/com/frolic/sns/global/config/spring/RedisConfigurationTest.java
Labels: test

#26 feat: add configuration that conigure WebMvc
  src/main/java/com/frolic/sns/global/config/spring/WebConfiguration.java
Labels: feature

#28 chore: update setting files
  conf/spring/application.example.dev.yaml
  conf/spring/application.example.prod.yaml
  docker-compose.yml
Labels: enhancement

#29 feat: twillio api 연동 및 테스트 작성 ( help required )
  build.gradle
  src/main/java/com/frolic/sns/auth/api/AuthApi.java
  src/main/java/com/frolic/sns/auth/application/AuthCodeCacheManager.java
  src/main/java/com/frolic/sns/auth/dto/UserFindEmailRequest.java
  src/main/java/com/frolic/sns/auth/dto/UserFindEmailRequestDto.java
  src/main/java/com/frolic/sns/auth/swagger/SendSMSDocs.java
  src/test/java/com/frolic/sns/auth/api/AuthSendSMSAptTest.java
Labels: help wanted, test, feature

#30 feat: add cache manager class object for manage authcode & code review for @Rungky
  conf/spring/application.example.prod.yaml
  src/main/java/com/frolic/sns/auth/api/AuthApi.java
  src/main/java/com/frolic/sns/auth/application/AuthCode.java
  src/main/java/com/frolic/sns/auth/application/AuthCodeCacheManager.java
  src/main/java/com/frolic/sns/auth/application/AuthManager.java
  src/main/java/com/frolic/sns/auth/application/EmailFindManager.java
  src/main/java/com/frolic/sns/auth/application/FinderType.java
  src/main/java/com/frolic/sns/global/config/spring/RedisConfiguration.java
  src/main/java/com/frolic/sns/global/config/spring/SmsTwilioConfiguration.java
  src/test/java/com/frolic/sns/auth/api/AuthSendSMSApiTest.java
  src/test/java/com/frolic/sns/auth/api/AuthSendSMSAptTest.java
  src/test/java/com/frolic/sns/auth/application/AuthCodeCacheManagerTest.java
Labels: refactor, test, feature

#32 feat: add config for redis host and port
  src/main/java/com/frolic/sns/global/config/spring/RedisConfiguration.java
Labels: feature

#33 feat: renew docker setttings
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/frolic/sns/global/config/spring/RedisConfiguration.java
Labels: feature

#31 Feat/fl 103 email 찾기 기능 코드 작성 오류
  src/main/java/com/frolic/sns/auth/api/AuthApi.java
  src/main/java/com/frolic/sns/auth/application/EmailFindManager.java
  src/main/java/com/frolic/sns/auth/application/UserInfoFindable.java
  src/main/java/com/frolic/sns/auth/swagger/FindEmailDocs.java
  src/main/java/com/frolic/sns/user/repository/UserRepository.java
Labels: question, feature

#35 feat: add EmailFindAPI
  build.gradle
  conf/spring/.example.env
  conf/spring/application.example.yaml
  src/main/java/com/frolic/sns/auth/api/SidType.java
  src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
  src/main/java/com/frolic/sns/auth/application/UserInfoFindable.java
  src/main/java/com/frolic/sns/auth/application/finder/EmailFindManager.java
  src/main/java/com/frolic/sns/auth/application/finder/FinderConstants.java
  src/main/java/com/frolic/sns/auth/application/finder/FinderType.java
  src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
  src/main/java/com/frolic/sns/auth/application/finder/TempPasswordCreator.java
  src/main/java/com/frolic/sns/auth/application/finder/UserInfoFinderSubManageable.java
  src/main/java/com/frolic/sns/auth/application/finder/UserInfoTransmittable.java
  src/main/java/com/frolic/sns/auth/application/finder/common/AuthCode.java
  src/main/java/com/frolic/sns/auth/application/finder/common/AuthCodeCacheManager.java
  src/main/java/com/frolic/sns/auth/application/finder/common/FinderConstants.java
  src/main/java/com/frolic/sns/auth/application/finder/common/FinderType.java
  src/main/java/com/frolic/sns/auth/application/finder/common/UserInfoFindManager.java
  src/main/java/com/frolic/sns/auth/application/finder/common/UserInfoFindable.java
  src/main/java/com/frolic/sns/auth/dto/UserFindEmailRequest.java
  src/main/java/com/frolic/sns/auth/dto/UserFindEmailRequestDto.java
  src/main/java/com/frolic/sns/auth/dto/UserFindEmailResponse.java
  src/main/java/com/frolic/sns/auth/dto/UserSignupRequest.java
  src/main/java/com/frolic/sns/auth/dto/VerifyCodeRequest.java
  src/main/java/com/frolic/sns/global/config/security/SpringSecurityConfiguration.java
  src/main/java/com/frolic/sns/global/config/spring/SmsTwilioConfiguration.java
  src/main/java/com/frolic/sns/global/exception/ErrorCode.java
  src/main/java/com/frolic/sns/global/exception/NotFoundCookieException.java
  src/test/java/com/frolic/sns/auth/api/AuthSignupApiTest.java
  src/test/java/com/frolic/sns/auth/api/UserEmailFinderApiTest.java
  src/test/java/com/frolic/sns/auth/application/AuthCodeCacheManagerTest.java
  src/test/java/com/frolic/sns/auth/application/finder/EmailFindManagerTest.java
  src/test/java/com/frolic/sns/auth/application/finder/TempPasswordCreatorTest.java
Labels: test, feature

#36 feat: Docker 빌드 자동화 대량 개선
  .Dockerignore
  .example.env
  .gitignore
  Dockerfile
  conf/local/.local.mariadb.env
  conf/local/.local.spring.example.env
  conf/local/docker-compose.yaml
  conf/local/nginx/nginx.conf
  conf/spring/application.example.prod.yaml
  src/main/java/com/frolic/sns/auth/application/finder/common/UserInfoFindable.java
Labels: documentation, feature

#38 chore: Gradle(groovy) -> Gradle(kotlin DSL) 변경 ( 오류 수정 포함 )
  build.gradle
  build.gradle.kts
  settings.gradle
  settings.gradle.kts
  src/main/java/com/frolic/sns/user/dto/UserUpdateRequest.java
  src/test/java/com/frolic/sns/user/api/UpdateUserInfoApiTest.java
  src/test/java/com/frolic/sns/util/TestUser.java
Labels: feature
