Repository geezers-io/frolic-backend, pull requests merged in 2023-03, with the labels that each got.

#48 chore: 도커 애플리케이션 동작 환경 개선
  conf/local/.local.spring.example.env
  conf/local/docker-compose.yaml
  docker-compose.yml
Labels: feature

#49 fix: isLikeUp 초기화 문제로 인한 에러 현상 해결
  src/main/java/com/frolic/sns/post/application/PostCrudManagerImpl.java
  src/main/java/com/frolic/sns/post/application/v2/CreatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/v2/HashTagManager.java
  src/main/java/com/frolic/sns/post/dto/PostInfo.java
  src/main/java/com/frolic/sns/post/dto/v2/CreatePostRequest.java
  src/main/java/com/frolic/sns/post/dto/v2/PostInfo.java
  src/main/java/com/frolic/sns/post/repository/HashtagDslRepository.java
Labels: bug

#51 feat: User 객체를 관리하는 클래스 작성
  src/main/java/com/frolic/sns/auth/application/auth/AuthManager.java
  src/main/java/com/frolic/sns/auth/application/finder/common/AuthCode.java
  src/main/java/com/frolic/sns/user/api/UserFollowManagementApi.java
  src/main/java/com/frolic/sns/user/api/UserManagementApi.java
  src/main/java/com/frolic/sns/user/application/UserFollowService.java
  src/main/java/com/frolic/sns/user/application/UserFollowServiceImpl.java
  src/main/java/com/frolic/sns/user/application/UserManageable.java
  src/main/java/com/frolic/sns/user/application/UserManager.java
  src/main/java/com/frolic/sns/user/application/UserService.java
  src/main/java/com/frolic/sns/user/repository/UserDslRepository.java
  src/main/java/com/frolic/sns/user/repository/UserRepository.java
  src/test/java/com/frolic/sns/auth/application/finder/SendTempPasswordManagerTest.java
  src/test/java/com/frolic/sns/user/api/UpdateUserInfoApiTest.java
Labels: refactor, feature

#52 feat: 파일 api 확장자 검사 수행 & docs
  conf/prod/.local.spring.example.env
  conf/spring/.example.env
  docker-compose.yml
  src/main/java/com/frolic/sns/global/common/file/api/FileApi.java
  src/main/java/com/frolic/sns/global/common/file/api/swagger/DownloadFileDocs.java
  src/main/java/com/frolic/sns/global/common/file/api/swagger/UploadFileDocs.java
  src/main/java/com/frolic/sns/global/common/file/application/FileExtensionValidator.java
  src/main/java/com/frolic/sns/global/common/file/application/ImageFileExtensionValidator.java
  src/main/java/com/frolic/sns/global/common/file/application/LocalFileService.java
  src/main/java/com/frolic/sns/global/common/file/application/S3FileService.java
  src/main/java/com/frolic/sns/global/common/jwt/JwtEntityLoader.java
  src/main/java/com/frolic/sns/global/exception/Error.java
  src/main/java/com/frolic/sns/global/exception/GlobalExceptionHandler.java
  src/main/java/com/frolic/sns/global/swagger/SwaggerMessageUtils.java
Labels: feature

#53 fix: 파일 검증 기능 테스트 작성 및 버그 수정
  src/main/java/com/frolic/sns/global/common/file/application/FileExtensionValidator.java
  src/main/java/com/frolic/sns/global/common/file/application/ImageFileExtensionValidator.java
  src/test/java/com/frolic/sns/auth/application/finder/EmailFindManagerTest.java
  src/test/java/com/frolic/sns/global/common/file/application/ImageFileExtensionValidatorTest.java
  src/test/java/com/frolic/sns/global/common/file/application/LocalApplicationFileServiceTestDeprecated.java
Labels: bug, test

#50 feat: 게시글 불러오기 v2 작성
  src/main/java/com/frolic/sns/post/api/CommentCrudApi.java
  src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
  src/main/java/com/frolic/sns/post/application/CommentCrudManager.java
  src/main/java/com/frolic/sns/post/application/CommentCrudService.java
  src/main/java/com/frolic/sns/post/application/PostFileManager.java
  src/main/java/com/frolic/sns/post/application/v2/CommentManager.java
  src/main/java/com/frolic/sns/post/application/v2/CreatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/v2/GetPostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/v2/PostCrudManagerV2.java
  src/main/java/com/frolic/sns/post/application/v2/UpdatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/dto/CreateCommentRequest.java
  src/main/java/com/frolic/sns/post/dto/PostInfo.java
  src/main/java/com/frolic/sns/post/dto/v2/GetPostCursorRequest.java
  src/main/java/com/frolic/sns/post/dto/v2/PostInfo.java
  src/main/java/com/frolic/sns/post/dto/v2/PostListResponse.java
  src/main/java/com/frolic/sns/post/model/Post.java
  src/main/java/com/frolic/sns/post/repository/CommentDslRepository.java
  src/main/java/com/frolic/sns/post/repository/CommentRepository.java
  src/main/java/com/frolic/sns/post/repository/LikeDslRepository.java
  src/main/java/com/frolic/sns/post/repository/PostDslRepository.java
  src/main/java/com/frolic/sns/post/repository/PostDslRespository.java
  src/main/java/com/frolic/sns/post/repository/PostFileRepository.java
Labels: draft, feature

#56 feat: QueryDsl 객체로 기존 역할 대체로 인한 코드 품질 향상 / 사용하지 않은 부분 제거 / v2 제거
  src/main/java/com/frolic/sns/FrolicApplication.java
  src/main/java/com/frolic/sns/global/common/file/model/ApplicationFile.java
  src/main/java/com/frolic/sns/global/common/file/repository/FileRepository.java
  src/main/java/com/frolic/sns/post/api/GetPostApi.java
  src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
  src/main/java/com/frolic/sns/post/api/PostLikeApi.java
  src/main/java/com/frolic/sns/post/application/CommentCrudService.java
  src/main/java/com/frolic/sns/post/application/CommentManager.java
  src/main/java/com/frolic/sns/post/application/CreatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/GetPostBusinessManager.java
  src/main/java/com/frolic/sns/post/application/GetPostService.java
  src/main/java/com/frolic/sns/post/application/HashTagManager.java
  src/main/java/com/frolic/sns/post/application/PostCrudManager.java
  src/main/java/com/frolic/sns/post/application/PostLikeManager.java
  src/main/java/com/frolic/sns/post/application/PostLikeService.java
  src/main/java/com/frolic/sns/post/application/UpdatePostBusinessManager.java
  src/main/java/com/frolic/sns/post/dto/GetPostCursorRequest.java
  src/main/java/com/frolic/sns/post/dto/PostListResponse.java
  src/main/java/com/frolic/sns/post/dto/v2/CreatePostRequest.java
  src/main/java/com/frolic/sns/post/repository/LikeDslRepository.java
  src/main/java/com/frolic/sns/post/repository/LikeRepository.java
  src/main/java/com/frolic/sns/user/application/UserService.java
Labels: refactor

#57 feat: 보안 로직 대규모 설계 개선 및 일부 로직 리팩터링
  src/main/java/com/frolic/sns/auth/api/AuthApi.java
  src/main/java/com/frolic/sns/auth/application/auth/AuthManageable.java
  src/main/java/com/frolic/sns/auth/application/auth/AuthManager.java
  src/main/java/com/frolic/sns/auth/application/auth/AuthService.java
  src/main/java/com/frolic/sns/auth/application/auth/RefreshTokenCacheManager.java
  src/main/java/com/frolic/sns/auth/application/auth/UserValidator.java
  src/main/java/com/frolic/sns/auth/application/finder/common/AuthCodeCacheManager.java
  src/main/java/com/frolic/sns/auth/application/security/FrolicAuthProvider.java
  src/main/java/com/frolic/sns/auth/application/security/FrolicAuthenticationToken.java
  src/main/java/com/frolic/sns/auth/application/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/frolic/sns/auth/application/security/JwtConstants.java
  src/main/java/com/frolic/sns/auth/application/security/JwtFilter.java
  src/main/java/com/frolic/sns/auth/application/security/JwtProvider.java
  src/main/java/com/frolic/sns/auth/application/security/JwtSecretKey.java
  src/main/java/com/frolic/sns/auth/application/security/TokenCreator.java
  src/main/java/com/frolic/sns/auth/application/security/TokenKey.java
  src/main/java/com/frolic/sns/auth/application/security/TokenType.java
  src/main/java/com/frolic/sns/auth/config/JwtProperties.java
  src/main/java/com/frolic/sns/auth/config/SpringSecurityConfig.java
  src/main/java/com/frolic/sns/auth/dto/AccessTokenInfo.java
  src/main/java/com/frolic/sns/global/common/jwt/JwtEntityLoader.java
  src/main/java/com/frolic/sns/global/config/security/CustomAuthProvider.java
  src/main/java/com/frolic/sns/global/config/security/CustomEmailPasswordAuthToken.java
  src/main/java/com/frolic/sns/global/config/security/JwtProvider.java
  src/main/java/com/frolic/sns/post/api/CommentCrudApi.java
  src/main/java/com/frolic/sns/post/application/CommentCrudService.java
  src/main/java/com/frolic/sns/post/application/PostLikeService.java
  src/main/java/com/frolic/sns/user/api/UserFollowManagementApi.java
  src/main/java/com/frolic/sns/user/api/UserManagementApi.java
  src/main/java/com/frolic/sns/user/application/UserFollowService.java
  src/main/java/com/frolic/sns/user/application/UserFollowServiceImpl.java
  src/main/java/com/frolic/sns/user/application/UserManager.java
  src/main/java/com/frolic/sns/user/application/UserService.java
  src/main/java/com/frolic/sns/user/application/info/UserEmail.java
  src/main/java/com/frolic/sns/user/application/info/UserName.java
  src/main/java/com/frolic/sns/user/repository/UserDslRepository.java
  src/main/java/com/frolic/sns/user/repository/UserRepository.java
  src/main/resources/application-jwt-config.yaml
  src/test/java/com/frolic/sns/auth/dto/TokenTypeDetailsDtoTest.java
Labels: refactor, feature

#59 feat: Gradle 스크립트 Kt DSL -> Groovy 변환 / 빌드 버그 해결
  Dockerfile
  build.gradle
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/com/frolic/sns/auth/api/AuthApi.java
  src/main/java/com/frolic/sns/auth/application/security/FrolicAuthenticationToken.java
  src/main/java/com/frolic/sns/post/dto/v2/PostInfo.java
  src/main/java/com/frolic/sns/user/application/UserManager.java
  src/test/java/com/frolic/sns/auth/api/AuthSigninApiTest.java
  src/test/java/com/frolic/sns/auth/api/AuthSignupApiTest.java
  src/test/java/com/frolic/sns/auth/api/UserEmailFinderApiTest.java
  src/test/java/com/frolic/sns/auth/api/UserTempPasswordApiTest.java
  src/test/java/com/frolic/sns/auth/application/finder/SendTempPasswordManagerTest.java
  src/test/java/com/frolic/sns/user/api/GetUserInfoApiTest.java
  src/test/java/com/frolic/sns/user/api/UpdateUserInfoApiTest.java
Labels: bug, feature

#60 feat: 빌드 스크립트 수정
  conf/prod/docker-compose.yaml
  conf/prod/nginx/nginx.conf
Labels: feature

#58 feat: 사용자 정보 찾기 시 sender 메일 주소 변경
  src/main/java/com/frolic/sns/auth/application/finder/EmailFindManager.java
  src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
  src/main/java/com/frolic/sns/auth/application/finder/UserFinderManageable.java
  src/main/java/com/frolic/sns/auth/application/finder/common/UserFinderManager.java
  src/main/java/com/frolic/sns/auth/application/finder/common/UserInfoFindable.java
  src/main/java/com/frolic/sns/auth/config/EmailManagerProperties.java
  src/main/java/com/frolic/sns/global/config/spring/SmsTwilioConfiguration.java
Labels: draft, feature

#63 feat: certbot 추가
  conf/prod/docker-compose.yaml
  conf/prod/nginx/nginx.conf
Labels: feature

#64 fix: 인증 관련 오류 발생 수정
  src/main/java/com/frolic/sns/auth/application/auth/AuthService.java
  src/main/java/com/frolic/sns/auth/application/security/FrolicAuthProvider.java
  src/main/java/com/frolic/sns/auth/application/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/frolic/sns/auth/swagger/AuthSchemas.java
  src/main/java/com/frolic/sns/auth/swagger/ReissueTokenDocs.java
  src/main/java/com/frolic/sns/global/exception/ErrorCode.java
  src/main/java/com/frolic/sns/user/repository/UserDslRepository.java
Labels: bug

#65 fix: ci 및 일부 api 이슈 수정
  src/main/java/com/frolic/sns/auth/application/security/FrolicAuthProvider.java
  src/main/java/com/frolic/sns/auth/config/SpringSecurityConfig.java
  src/main/java/com/frolic/sns/user/dto/PasswordUpdateRequest.java
  src/test/java/com/frolic/sns/auth/application/finder/EmailFindManagerTest.java
Labels: bug
